// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIdentity struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Email         string
	PasswordHash  string
	EmailVerified pgtype.Bool
	RevokedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type OutboxEvent struct {
	ID          pgtype.UUID
	EventType   string
	Payload     []byte
	Status      string
	LockedBy    pgtype.Text
	LockedAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}
