// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: outbox_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOutboxEvents = `-- name: GetOutboxEvents :many
SELECT id, event_type, payload 
FROM outbox_events
WHERE (
    status = 'PENDING'
    OR (status = 'PROCESSING' AND locked_at < now() - interval '30 seconds')
)
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type GetOutboxEventsRow struct {
	ID        pgtype.UUID
	EventType string
	Payload   []byte
}

func (q *Queries) GetOutboxEvents(ctx context.Context, limit int32) ([]GetOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutboxEventsRow
	for rows.Next() {
		var i GetOutboxEventsRow
		if err := rows.Scan(&i.ID, &i.EventType, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO 
outbox_events (event_type, payload)
VALUES ($1, $2)
`

type InsertOutboxEventParams struct {
	EventType string
	Payload   []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.EventType, arg.Payload)
	return err
}

const lockOutboxEvents = `-- name: LockOutboxEvents :execrows
UPDATE outbox_events
SET 
    status = 'PROCESSING',
    locked_by = $1,
    locked_at = now()
WHERE id = ANY($2::UUID[])
`

type LockOutboxEventsParams struct {
	LockedBy pgtype.Text
	Column2  []pgtype.UUID
}

func (q *Queries) LockOutboxEvents(ctx context.Context, arg LockOutboxEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, lockOutboxEvents, arg.LockedBy, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :execrows
UPDATE outbox_events
SET
    status = 'PROCESSED',
    processed_at = now()
WHERE id = ANY($1::UUID[])
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, dollar_1 []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventProcessed, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
